#!/bin/bash
clear
echo -e "************************************************************"
echo -e "******************* WELCOME TO JAVANET *********************"
echo -e "***************** Auto Script By jAvaNet *******************"
echo -e "**LINE:javanet *** Whatsapp:+60179692548 *****FB:javajaja***"
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "* menu         : สารบัญคำสั่ง"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     SSH AND OPENVPN"
echo -e "* usernew      : สร้างบัญชี SSH & OpenVPN"
echo -e "* trial        : สร้างบัญชีทดลอง SSH & OpenVPN"
echo -e "* renew        : ต่ออายุบัญชี SSH & OpenVPN"
echo -e "* deluser      : ลบบัญชี SSH & OpenVPN"
echo -e "* cek          : แสดงบัญชีผู้ใช้งาน SSH & OpenVPN"
echo -e "* member       : แสดงบัญชี SSH & OpenVPN ทั้งหมด"
echo -e "* delete       : ลบบัญชี SSH & OpenVPN ที่หมดอายุแล้ว"
echo -e "* autokill     : ตั้งค่าการเข้าใช้งานหลายบัญชี"
echo -e "* ceklim       : แสดงบัญชีที่เข้าใช้งานหลายเครื่อง"
echo -e "* restart      : รีสตาร์ท  Dropbear, Squid3, OpenVPN และ SSH"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     WIREGUARD"
echo -e "* add-wg       : สร้างบัญชี  Wireguard"
echo -e "* del-wg       : ลบบัญชี  Wireguard"
echo -e "* cek-wg       : ตรวจสอบผู้ใช้งาน Wireguard"
echo -e "* renew-wg     : ต่ออายุบัญชี  Wireguard"
echo -e "* wg show      : แสดงสถานะการใช้งาน Wireguard"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     L2TP"
echo -e "* add-l2tp     : สร้างบัญชี  L2TP"
echo -e "* del-l2tp     : ลบบัญชี L2TP"
echo -e "* renew-l2p    : ต่ออายุบัญชี L2TP"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     PPTP"
echo -e "* add-pptp     : สร้างบัญชี PPTP"
echo -e "* del-pptp     : ลบบัญชี PPTP"
echo -e "* renew-pptp   : ต่ออายุบัญชี  PPTP"
echo -e "* cek-pptp     : แสดงบัญชีผู้ใช้งาน PPTP"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     SSTP"
echo -e "* add-sstp     : สร้างบัญชี SSTP"
echo -e "* del-sstp     : ลบบัญชี SSTP"
echo -e "* renew-sstp   : ต่ออายุบัญชี SSTP"
echo -e "* cek-sstp     : แสดงบัญชีผู้ใช้งาน SSTP"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     VMESS"
echo -e "* add-ws       : สร้างบัญชี VMESS"
echo -e "* del-ws       : ลบบัญชี VMESS"
echo -e "* cek-ws       : ตรวจสอบผู้ใช้งานบัญชี VMESS"             
echo -e "* renew-ws     : ต่ออายุบัญชี VMESS"                     
echo -e "* cert2vray    : ต่ออายุ Certificate ของบัญชี VMESS"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     TROJAN"
echo -e "* add-tr       : สร้างบัญชี TROJAN"
echo -e "* del-tr       : ลบบัญชี TROJAN"
echo -e "* cek-tr       : ตรวจสอบผู้ใช้งานบัญชี TROJAN"             
echo -e "* renew-tr     : ต่ออายุบัญชี TROJAN"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     VLESS"
echo -e "* add-vless    : สร้างบัญชี VLESS"
echo -e "* del-vless    : ลบบัญชี VLESS"
echo -e "* cek-ws       : ตรวจสอบผู้ใช้งานบัญชี VLESS"             
echo -e "* renew-vless  : ต่ออายุบัญชี VLESS"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     SHADOWSOCK-R"
echo -e "* add-ssr      : สร้างบัญชี SSR"
echo -e "* del-ssr      : ลบบัญชี SSR"
echo -e "* ssr          : แสดงเมนู SSR เพิ่มเติม"             
echo -e "* renew-ssr    : ต่ออายุบัญชี SSR"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                     SHADOWSOCK-S OBFS"
echo -e "* add-ss       : สร้างบัญชี SS"
echo -e "* del-ss       : ลบบัญชี SS"
echo -e "* cek-ss       : ตรวจสอบผู้ใช้งานบัญชี SS"             
echo -e "* renew-ss     : ต่ออายุบัญชี SS"
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "                    ตั้งค่าระบบ"
echo -e ""
echo -e "* add-host     : เพิ่มโฮตส์หรือซับโดเมน"
echo -e "* change-port  : แก้ไขหรือเปลี่ยนพอร์ต"
echo -e "* autobackup   : แบ็คข้อมูลอัตโนมัติ"
echo -e "* backup       : แบ็คอัพข้อมูล "
echo -e "* restore      : รีสตอร์ข้อมูล "
echo -e "* wbmn         : ติดตั้งWebmin"
echo -e "* kernel-updt  : อัพเดทKernel"
echo -e "* limit-speed  : จำกัดแบนด์วิธ"
echo -e "* ram          : ตรวจสอบแรม"
echo -e "* reboot       : รีบูตเครื่อง"
echo -e "* speedtest    : ตรวจสอบความเร็วเซิฟเวอร์"
echo -e "* update       : อัพเดทสคริป"
echo -e "* about        : ข้อมูลเกี่ยวกับสคริป "
echo -e "* info         : แสดงข้อมูลระบบ"
echo -e "* exit         : ออก "
echo -e ""
echo -e "************************************************************"
echo -e "************************************************************"
echo -e ""
echo -e "  ขอบคุณมากที่ใช้บริการของเรา"
echo -e ""
echo -e " Copyright ©jAvaNet"
echo -e ""
